name: 'POM and Changelog Version Bump'
description: 'Find the current version and bump it OR explicitly set the version number and update the changelog accordingly'
branding:
  icon: box
  color: blue
inputs:
  bumpVersionType:
    description: 'Parameter to bump version number or set version number'
    required: false
    default: 'bump'
  bumpVersion:
    descriptio n: 'Version bump type; major, minor, or patch'
    required: false
    default: 'patch'
  setVersion:
    description: 'Version number to explicitly set'
    required: false
  pomLocations:
    description: 'Location of pom file(s)'
    required: false
    default: 'pom.xml'
  bumpChangelog:
    description: 'Add changelog entry; true or false'
    required: false
    default: 'false'  
  changelogDesc:
    description: 'Changelog message, PR title should be used by Dependabot'
    required: false
outputs:
  versionNumber: # id of output
    description: 'Updated Version Number'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bumpVersionType }}
    - ${{ inputs.bumpVersion }}
    - ${{ inputs.setVersion }}
    - ${{ inputs.pomLocations }}
    - ${{ inputs.bumpChangelog }}
    - ${{ inputs.changelogDesc }}
