on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to bump POM and ChangeLog
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Uses POM Version Bump
        uses: ./ #Uses an action in the root directory
        id: bump
        with:
          bumpVersionType: bump
          bumpVersion: patch
          bumpChangelog: true
          changelogDesc: ${{ github.event.pull_request.title }}
      - name: Get the version number
        run: echo "The Version Number is ${{ steps.bump.outputs.versionNumber }}"